### ISSUE TITLE
What has been changed in gengtype-lex as compared to standard gcc10?

### ISSUE THREAD

**Issue by barracuda156** [iains/gcc-10-branch#6]
@iains In an attempt build `gcc10` natively on 10A190 I bumped into a surprising phenomenon.

When I tried to build your `gcc10ppc` branch, it failed rather soon with `gengtype-lex` fatal error and a long list of undefined symbols. While building a standard `gcc10` still fails eventually, compilation proceeds well beyond the previous error point.

Is it a coincidence or there were some changes to that part of the code made which could result in such an effect (assuming a hybrid OS between 10.5 and 10.6 in terms of behavior)?

**Comment by iains** [comment]
nothing has changed in those sources

I am sorry, but there is absolutely no way to support the work you are doing with a mixture of OS releases ..

**Comment by barracuda156** [comment]
> but there is absolutely no way to support the work you are doing with a mixture of OS releases ..

Please excuse me. I did not imply I want anything to be done in this regard.
Your answer is sufficient, I will look into the cause of the issue myself.
